#!/bin/bash
    
# Config
if [[ -z "${OCIE_CONFIG}" ]];then
    echo "Ocie: Environment variable [ OCIE_CONFIG ] is not set";
    echo "Ocie: Create an 'config.ocie' in your application, set the environment OCIE_CONFIG, e.g OCIE_CONFIG=/etc/myapp/path_to_definition";
    exit 1;
fi;
if [[ ! -f "${OCIE_CONFIG}/config.ocie" ]];then
    echo "Ocie: Unable to load config, [ ${OCIE_CONFIG} ] is not a directory or [ ${OCIE_CONFIG}/config.ocie ] is not readable";
    exit 1;
fi;
    
# Include app config
. ${OCIE_CONFIG}/config.ocie;
    
function show_help()
{
    echo "OCIE Application Control";
    echo
    echo "Syntax: ociectl [ --reload | --run | --stop ]";
    echo
    echo "Parameters:";
    echo
    echo "--reload   Reload the application";
    echo
    echo "--run      Run the application";
    echo
    echo "--stop     Stop the application";
    echo
    echo "--test     Test the applications config";
    echo
}
    
function check_volumes()
{
    if [[ ! -z "${APP_VOLS}" ]];then
        local unmapped="";
        local vols=$(cat /proc/mounts);
        for i in ${APP_VOLS//:/ };do
            if [[ -z "$(echo $vols | grep -o '$i')" ]];then
                unmapped+="$i, ";
            fi;
        done;
        if [[ ! -z "$unmapped" ]];then
            echo "Ocie: Application needs to store persistant data and the volume(s) listed are not mapped:";
            echo "  [ ${unmapped%, } ]";
            echo "Ocie: Each volume should be mapped at runtime , e.g --volume my_vol:/example/path";
            echo "Ocie: If this is a development environment, set --env|-e APP_ENV='dev' to mute this warning";
        fi;
    fi;
}
    
function ocie_shutdown()
{
    echo "Ocie: Recieved stop signal, attemtping to terminate application gracefully";
    app_shutdown;
    echo "Ocie: Application stopped with exit code [ $? ], shutting down container..";
    exit 0;
}
    
function ocie_certs()
{
    if [[ "${CA_ENABLED}" == 1 ]];then
        if [[ $(type -t app_certs) == function ]];then
            app_certs;
        fi;
    else
        echo "Ocie: CA Import is DISABLED, set CA_ENABLED=1 in order activate, skipping..";
    fi;
}
    
function ocie_config()
{
    if [[ $(type -t app_config) == function ]];then
        app_config;
    fi;
}
    
function ocie_keys()
{
    if [[ "${CERT_ENABLED}" == 1 ]];then
        if [[ $(type -t app_keys) == function ]];then
            app_keys;
        fi;
    else
        echo "Ocie: Certificate keygen is DISABLED, set CERT_ENABLED=1 in order activate, skipping..";
    fi;
}
    
function ocie_deploy()
{
    if [[ "${APP_DEPLOY}" == 1 ]];then
        if [[ $(type -t app_deploy) == function ]];then
            app_deploy;
        fi;
    else
        echo "Ocie: App Deployment/Update is DISABLED, set APP_DEPLOY=1 in order activate, skipping..";
    fi;
}
    
function ocie_test()
{
    if [[ $(type -t app_test) == function ]];then
        echo $(app_test);
    fi;
}
    
function ocie_reload()
{
    echo "Ocie: Reloading application";
    app_reload;
}
    
function ocie_start()
{
    ocie_certs;
    ocie_keys;
    ocie_config;
    ocie_deploy;
    if [[ "${APP_ENV}" == "prod" ]];then
        check_volumes;
    fi;
    echo "Ocie: Initialization complete";
    echo "Ocie: Application starting, please wait...";
    if [[ "${WATCHER_ENABLED}" == "1" ]];then
        local pid=$(app_start);
        if [[ ! -z "$pid" ]];then
            echo "Ocie: Application started, watching PID: [ $pid ], Interval: [ ${WATCHER_INTERVAL} ]";
            echo "Ocie: Press CTRL+C to stop";
        else
            echo "Ocie: Application did not return a PID";
            ocie_shutdown;
        fi;
        while true;do
            if [[ -z $(ps --no-headers -p $pid) ]];then
                echo "Ocie: Application process has disappeared";
                ocie_shutdown;
            fi;
            sleep ${WATCHER_INTERVAL};
        done;
    else
        echo "Ocie: Watcher is DISABLED, not monitoring process";
        echo "Ocie: Ensure your start script maintains the process or is started in console/foreground mode";
        echo "Ocie: You can set WATCHER_ENABLED=1 to run your application in the background";
        app_start;
    fi;
}
    
# Shutdown - SIGINT, SIGTERM, SIGWINCH
trap ocie_shutdown 2 15 28
    
for cmds in "$@";do
    shift;
    case "$cmds" in
        '--help')
            show_help;;
        '--reload')
            ocie_reload;;
        '--run')
            ocie_start;;
        '--stop')
            ocie_shutdown;;
        '--test')
            ocie_test;;
        *);;
    esac;
done;
