#!/bin/bash
    
. ${OCIE_LIB}/include/apache;
    
# Tomcat specific
app_proxies="$(echo ${VADC_IP_ADDRESS// /|} | sed 's/\./\\./g' | sed 's|\/|\\/|g')";
if [[ -f "${OCIE_HOME}/conf/ocie-tomcat.init" ]];then
    reset_config;
fi;
    
function apache_mod_jk()
{
    cp "${APACHE_MODS}/jk.conf.dist" "${APACHE_MODS}/jk.conf" >/dev/null 2>&1;
    cp "${APACHE_MODS}/jk.load.dist" "${APACHE_MODS}/jk.load" >/dev/null 2>&1;
}
    
function tomcat_set_env()
{
    echo "export JAVA_OPTS=\"${JAVA_OPTS} ${APP_PARAMS}\"" > ${CATALINA_HOME}/bin/setenv.sh
    echo "export VADC_IP_REG=\"${app_proxies}\"" >> ${CATALINA_HOME}/bin/setenv.sh
    chown ${APP_OWNER}:${APP_GROUP} "${CATALINA_HOME}/bin/setenv.sh";
    chmod a+x "${CATALINA_HOME}/bin/setenv.sh";
}
    
function tomcat_server_cfg()
{
    if [[ -f "${CATALINA_HOME}/conf/server.xml" ]];then
        mv "${CATALINA_HOME}/conf/server.xml" "${CATALINA_HOME}/conf/server.xml.previous" >/dev/null 2>&1;
    fi;
    if [[ -f "${CATALINA_HOME}/conf/server.xml.dist" ]];then
        cp "${CATALINA_HOME}/conf/server.xml.dist" "${CATALINA_HOME}/conf/server.xml" >/dev/null 2>&1;
    fi;
}
    
# Set environment 
tomcat_set_env;
# Enable libapache2-mod-jk
apache_mod_jk;
    
# Ensure config is valid
catalina_cfg=$(ociectl --test);
if [[ ! -z "${catalina_cfg}" ]];then
    echo "Ocie Config: Tomcat config test FAILED, reverting changes";
    echo "Ocie Config: Result: ${catalina_cfg}";
    reset_config;
    exit 1;
fi;
    
# Set ready
echo "Ocie Config: Tomcat Config Test PASSED, using updated configuration";
echo "Ocie Config: Tomcat RemoteIpValve configured with [internalProxies: ${app_proxies}, remoteIpHeader: ${VADC_IP_HEADER}]";
echo "Ocie Config: Configured JAVA_OPTS with ${APP_PARAMS}";
echo "#Tomcat Initialized" > ${OCIE_HOME}/conf/ocie-tomcat.init;
