#!/bin/bash
    
# This utils helper should be sourced, e.g  . ${OCIE_LIB}/include/utils
# Print/Log/Output Message OR mute if OCIE_SILENT=1, e.g --quiet
function print_msg()
{
    if [[ ! -z "$1" ]];then
        if [[ ! "${OCIE_SILENT}" == 1 ]];then
            echo "$1";
        else
            echo "$1" >> ${OCIE_LOG}/console-$(date '+%Y-%m').log
        fi;
    else
        while IFS= read -r line;do
            if [[ ! "${OCIE_SILENT}" == 1 ]];then
                echo "$line";
            else
                echo "$line" >> ${OCIE_LOG}/console-$(date '+%Y-%m').log
            fi;
        done;
    fi;
}
    
# Get sha1 OR sha256 signature of directory/file, default: sha1
function get_signature()
{
    object="$1";
    option="${2,,}";
    if [[ -z "${option}" ]];then
        option='sha1';
    fi;
    if [[ ! "${option}" == "sha1" ]] && [[ ! "${option}" == "sha256" ]];then
        option='sha1';
    fi;
    if [[ -d "${object}" ]];then
        echo "$(find ${object} -type f -print0 | xargs -0 sha1sum | sort | sha1sum | cut -f1 -d' ')";
    elif [[ -f "${object}" ]];then
        echo "$(${option}sum ${object} | cut -f1 -d' ')";
    else
        echo "0";
    fi;
}
