#!/bin/bash
    
CA_FILTER="${CA_FILTER:-*_CA.crt}";
CA_PATH="${CA_PATH:-}";
CA_UPDATE_AUTO="${CA_UPDATE_AUTO:-1}";
CA_UPDATE_OS="${CA_UPDATE_OS:-0}";
CA_UPDATE_JVM="${CA_UPDATE_JVM:-0}";
JAVA_PATH="${JAVA_HOME:-/usr}";
    
function show_help()
{
   echo "Update CA Certificate Stores"
   echo
   echo "Syntax: cacerts --os --jvm --path 'https://certs.example.com/'";
   echo "    If neither of --os, --jvm are defined, importer will attempt both."
   echo
   echo "Required:"
   echo "    --path <path>    Path to import CA Certs from, prefixed with either [ url: | file:file ],";
   echo "                     e.g file:/opt/certs OR url:https://certs.example.com";
   echo
   echo "Optional:";
   echo "    --os        Import into operating system store, /etc/ssl";
   echo "    --jvm       Import into java store, cacerts. Ensure JAVA_HOME is set, fallback to /usr/bin/java if available";
   echo "    --filter    Filter to find CA cert files by, default: *_CA.crt";
}
    
function get_certs()
{
    cd /usr/local/share/ca-certificates;
    if [[ "${PATH_TYPE}" == "url" ]];then
        wget -q -r -nH -A "${CA_FILTER}" "${IMPORT_PATH}";
    else 
        if [ -d "${IMPORT_PATH}" ];then
            cp -R "${IMPORT_PATH}/${CA_FILTER}" /usr/local/share/ca-certificates/;
        else
            echo "Ocie: CA Import: Unable to read [ ${CA_PATH} ] or it is not a valid directory";
        fi;
    fi;
}
    
function import_auto()
{
    import_os;
    if [[ -f "${JAVA_PATH}/bin/keytool" ]];then
        import_jvm;
    fi;
}
    
function import_jvm()
{
    for ca_crt in /usr/local/share/ca-certificates/*.crt; do
        ca_name=$(openssl x509 -noout -subject -nameopt multiline -in $ca_crt | tr -d ' ' | grep -o 'commonName=.*' | cut -f2 -d'=');
        ca_exists=$(${JAVA_PATH}/bin/keytool -list -cacerts -storepass changeit -alias "$ca_name" | echo $?);
        if [ "$ca_exists" -eq 0 ];then
            $JAVA_PATH/bin/keytool \
            -import -trustcacerts -cacerts -storepass changeit -noprompt -alias "$ca_name" -file "$ca_crt" >/dev/null 2>&1 \
            | echo "Ocie: CA Import: Added certificate to java trust store: [ $ca_crt ]";
        else 
            echo "Ocie: CA Import: Certificate [ ${ca_name} ] already exists, skipping";
        fi;
    done;
}
    
function import_os()
{
    local certs=$(ls /usr/local/share/ca-certificates/*.crt 2> /dev/null | wc -l);
    if [ "$certs" -ne 0 ];then
        update-ca-certificates &> /dev/null;
    else
        echo "Ocie: CA Import: No certificates were found to import";
    fi;
}
    
function cert_import()
{
    if [[ "${CA_UPDATE_AUTO}" == 1 ]];then
        echo "Ocie: CA Import: Auto Update is enabled";
        import_auto;
    else
        if [[ "${CA_UPDATE_OS}" == 1 ]];then
            echo "Ocie: CA Import: Updating OS CA Store";
            import_os;
        fi;
        if [[ "${CA_UPDATE_JVM}" == 1 ]];then
            if [[ -f "$JAVA_PATH/bin/keytool" ]];then
                echo "Ocie: CA Import: Updating JVM CA Store";
                import_jvm;
            else
                echo "Ocie: CA Import: Unable to locate a java binary, [ JAVA_HOME ] is not set or [ /usr/bin/java ] not found, skipping";
            fi;
        fi;
    fi;
}
    
function cleanup()
{
    cd /usr/local/share/ca-certificates;
    rm -rf /usr/local/share/ca-certificates/*;
}
    
for cmds in "$@";do
    shift;
    case "$cmds" in
        '--help')
            show_help;;
        '--os')
            CA_UPDATE_OS=1;;
        '--jvm')
            CA_UPDATE_JVM=1;;
        '--path')
            CA_PATH="$1";;
        '--filter')
            CA_FILTER="$1";;
        *);;
    esac;
done;
    
#Run
if [[ ! -z "${CA_PATH}" ]];then
    IMPORT_PATH="${CA_PATH#*:}";
    PATH_TYPE="${CA_PATH%%:*}";
    if [[ ! "${PATH_TYPE}" == "file" ]] && [[ ! "${PATH_TYPE}" == "url" ]];then
        echo "Ocie: CA Import: Unable to determine CA_PATH type, [ ${PATH_TYPE} ], only file: or url: are valid";
    else
        echo "Ocie: CA Import: Starting";
        get_certs;
        cert_import;
        cleanup;
        echo "Ocie: CA Import: Finished";
    fi;
else
    echo "Ocie: CA Import: --path | env CA_PATH is not defined, skipping";
fi;
