#!/bin/bash
    
function get_signature()
{
    option="$1";
    object="$2";
    if [[ -d "${object}" ]];then
        set_metadata "${option}" "${object}";
        echo "$(sha1sum ${APP_CACHE}/${APP_NAME}.${option}.metadata | awk '{print $1}')";
    elif [[ -f "${object}" ]];then
        echo "$(sha1sum ${object} | awk '{print $1}')";
    else
        echo "0";
    fi;
}
    
function set_metadata()
{
    option="$1";
    object="$2";
    if [[ -f "${APP_CACHE}/${APP_NAME}.${option}.metadata" ]];then
        rm "${APP_CACHE}/${APP_NAME}.${option}.metadata";
    fi;
    (
        cd "${object}";
        for i in *;do 
            sha1sum "$i"; 
        done;
    ) >> "${APP_CACHE}/${APP_NAME}.${option}.metadata";
    cd /opt;
}
    
function deploy_app()
{
    if [[ -d "${APP_LATEST}" ]];then
        cp -R ${APP_LATEST}/* ${APP_HOME};
    else
        cp -R ${APP_LATEST} ${APP_HOME};
    fi;
}
    
function update_app()
{
    if [[ "${SIG_LOCAL}" == "${SIG_UPDATE}" ]];then
        echo "Ocie Updater: Update is not needed, deployed: ${SIG_LOCAL}, latest: ${SIG_UPDATE}";
    fi;
    if [[ "${APP_UPDATE_AUTO}" == 1 ]];then
        deploy_app;
    fi;
}
    
#Run
    
if [[ "${APP_UPDATE_PATH}" == "" ]];then
    echo "Ocie Updater: Nothing to do";
else
    if [[ "${APP_TYPE}" == "" ]];then
        echo "Ocie Updater: Required APP_TYPE is not set";
        exit 22;
    elif [[ "${APP_NAME}" == "" ]];then
        echo "Ocie Updater: Required APP_NAME is not set";
        exit 22;
    else
        echo "Ocie Updater: Checking if deployment or update needed";
    fi;
    
    echo "Ocie Updater: APP_TYPE is ${APP_TYPE}";
    
    if [[ "${APP_TYPE}" == "apache" ]];then
        APP_HOME="/var/www/html";
        APP_DEPLOY="/var/www/html";
        APP_LATEST="${APP_UPDATE_PATH}/${APP_NAME}";
    fi;
    
    if [[ "${APP_TYPE}" == "tomcat" ]];then
        APP_HOME="${CATALINA_HOME}/webapps/";
        APP_DEPLOY="${APP_HOME}${APP_NAME}.war";
        APP_LATEST="${APP_UPDATE_PATH}/${APP_NAME}.war";
        if [[ "${APP_DATA}" == "/var/www/html" ]];then
            APP_DATA="/etc/${APP_NAME}";
            echo "Ocie Updater: APP_DATA is set to /var/www, changing to ${APP_DATA}";
        fi;
        if [[ "${APP_OWNER}" == "www-data" ]];then
            APP_OWNER="root";
            echo "Ocie Updater: APP_OWNER is set to www-data, changing to ${APP_OWNER}";
        fi;
        if [[ "${APP_GROUP}" == "www-data" ]];then
            APP_GROUP="tomcat";
            echo "Ocie Updater: APP_GROUP is set to www-data, changing to ${APP_GROUP}";
        fi;
    fi;
    
    if [[ ! -d "${APP_DATA}" ]]; then
        echo "Ocie Updater: Data directory for application does not exist, creating ${APP_DATA}";
        install -d -m 0770 -o ${APP_OWNER} -g ${APP_GROUP} ${APP_DATA};
    fi
    
    SIG_LOCAL=$(get_signature "local" "${APP_DEPLOY}");
    SIG_UPDATE=$(get_signature "update" "${APP_LATEST}");
    
    if [[ "${SIG_LOCAL}" == "0" ]] && [[ "${SIG_UPDATE}" == "0" ]];then
        echo "Ocie Updater: Application has not been deployed and was not found in ${APP_UPDATE_PATH}";
        exit 2;
    elif [[ "${SIG_LOCAL}" == "0" ]] && [[ "${SIG_UPDATE}" != "0" ]];then
        echo "Ocie Updater: Application has not been deployed, deploying from ${APP_UPDATE_PATH}";
        deploy_app;
    elif [[ "${SIG_LOCAL}" != "0" ]] && [[ "${SIG_UPDATE}" == "0" ]];then
        echo "Ocie Updater: Application is deployed but update is empty, failure enabled: ${APP_UPDATE_FAIL}";
        if [[ "${APP_UPDATE_FAIL}" == 1 ]];then
            exit 2;
        fi;
    else
        echo "Ocie Updater: Auto-update is enabled: ${APP_UPDATE_AUTO}, deployed: ${SIG_LOCAL}, latest: ${SIG_UPDATE}";
        update_app;
    fi;
fi;
